name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Run Python code
        run: cd ../../ 
             python main.py  # Replace 'your_script.py' with the actual name of your Python script

