name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Python code
        run: python main.py  # Replace 'your_script.py' with the actual name of your Python script

      - name: Display Python code output
        run: cat output.txt  # Assuming your Python code writes output to a file named 'output.txt'
